
from datetime import datetime

class RoutingCommand:
    """Interface of the application data type RoutingCommand. 
       Generated by: EASy-Producer."""
 
    
    def getCmd(self) -> str:
        """Returns the value of {@code cmd}.
        
           Returns:
             - the value of cmd"""
        raise NotImplementedError
    
    
    def setCmd(self, v: str):
        """Changes the value of {@code cmd}.
        
           Parameters:
             - v -- the new value of cmd"""
        raise NotImplementedError
    
