
from datetime import datetime

class RoutingConnOut:
    """Interface of the application data type RoutingConnOut. 
       Generated by: EASy-Producer."""
 
    
    def getSerNr(self) -> int:
        """Returns the value of {@code serNr}.
        
           Returns:
             - the value of serNr"""
        raise NotImplementedError
    
    def getData(self) -> str:
        """Returns the value of {@code data}.
        
           Returns:
             - the value of data"""
        raise NotImplementedError
    
    
    def setSerNr(self, v):
        """Changes the value of {@code serNr}.
        
           Parameters:
             - v -- the new value of serNr, may be of type int or the corresponding numpy type"""
        raise NotImplementedError
    
    def setData(self, v: str):
        """Changes the value of {@code data}.
        
           Parameters:
             - v -- the new value of data"""
        raise NotImplementedError
    
