package iip.stubs;

import de.iip_ecosphere.platform.services.environment.*;
import de.iip_ecosphere.platform.support.aas.InvocablesCreator;
import iip.datatypes.*;
import iip.interfaces.*;

/**
 * IIP-Ecosphere service stub for net node 'ParallelRoutingProcessor2'.
 * Generated by: EASy-Producer.
 */
public class ParallelRoutingProcessor2Stub extends ServiceStub implements ParallelRoutingProcessor2Interface {

    /**
     * Creates the setup and registers the operations.
     * 
     * @param iCreator the AAS invocables creator
     * @param serviceId the service id to create the qualified names via {@link ServiceMapper#getQName(Service, String)}
     */
    public ParallelRoutingProcessor2Stub(InvocablesCreator iCreator, String serviceId) {
        super(iCreator, serviceId);
    }
    
    public void processRoutingTestData(RoutingTestData data) {
        // TODO connect via VAB
    }
    public void processRoutingCommand(RoutingCommand data) {
        // TODO connect via VAB
    }
    @Override
    public void attachRoutingTestDataIngestor(DataIngestor<RoutingTestData> ingestor) {
        // TODO clarify with Impl
    }
}
