package iip.stubs;

import de.iip_ecosphere.platform.services.environment.*;
import de.iip_ecosphere.platform.support.aas.InvocablesCreator;
import iip.datatypes.*;
import iip.interfaces.*;

/**
 * IIP-Ecosphere service stub for net node 'RoutingSink'.
 * Generated by: EASy-Producer.
 */
public class RoutingSinkStub extends ServiceStub implements RoutingSinkInterface {

    /**
     * Creates the setup and registers the operations.
     * 
     * @param iCreator the AAS invocables creator
     * @param serviceId the service id to create the qualified names via {@link ServiceMapper#getQName(Service, String)}
     */
    public RoutingSinkStub(InvocablesCreator iCreator, String serviceId) {
        super(iCreator, serviceId);
    }
    
    public void processRoutingTestData(RoutingTestData data) {
        // TODO connect via VAB
    }
    @Override
    public void attachRoutingCommandIngestor(DataIngestor<RoutingCommand> ingestor) {
        // TODO clarify with Impl
    }
}
