package iip.stubs;

import de.iip_ecosphere.platform.services.environment.*;
import de.iip_ecosphere.platform.support.aas.InvocablesCreator;
import iip.datatypes.*;
import iip.interfaces.*;

/**
 * IIP-Ecosphere service stub for net node 'myKi example'.
 * Generated by: EASy-Producer.
 */
public class MyKiExampleStub extends ServiceStub implements MyKiExampleService {

    /**
     * Creates the setup and registers the operations.
     * 
     * @param iCreator the AAS invocables creator
     * @param serviceId the service id to create the qualified names via {@link ServiceMapper#getQName(Service, String)}
     */
    public MyKiExampleStub(InvocablesCreator iCreator, String serviceId) {
        super(iCreator, serviceId);
    }
    
    public String transformRec1String(Rec1 data) {
        return null; // TODO connect via VAB
    }

    
}
