/*
 * generated by Xtext 2.34.0
 */
package de.uni_hildesheim.sse.vil.templatelang.parser.antlr;

import com.google.inject.Inject;
import de.uni_hildesheim.sse.vil.templatelang.parser.antlr.internal.InternalTemplateLangParser;
import de.uni_hildesheim.sse.vil.templatelang.services.TemplateLangGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TemplateLangParser extends AbstractAntlrParser {

	@Inject
	private TemplateLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTemplateLangParser createParser(XtextTokenStream stream) {
		return new InternalTemplateLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "LanguageUnit";
	}

	public TemplateLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TemplateLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
