/*
* generated by Xtext
*/
package de.uni_hildesheim.sse.vil.expressions.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.uni_hildesheim.sse.vil.expressions.services.ExpressionDslGrammarAccess;

public class ExpressionDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ExpressionDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.uni_hildesheim.sse.vil.expressions.parser.antlr.internal.InternalExpressionDslParser createParser(XtextTokenStream stream) {
		return new de.uni_hildesheim.sse.vil.expressions.parser.antlr.internal.InternalExpressionDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "LanguageUnit";
	}
	
	public ExpressionDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ExpressionDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
