package iip.datatypes;


/**
 * Implementation of the application data type MyConnMachineIn.
 * Generated by: EASy-Producer.
 */
public class MyConnMachineIn {
 
    private String dataField;
    
    private int axis;
    
    private String cmdField;
    

    /**
     * Default constructor. Fields are pre-allocated with default Java values.
     */
    public MyConnMachineIn() {
    }
    
    /**
     * Copy constructor.
     * 
     * @param from the instance to copy the values from
     */
    public MyConnMachineIn(MyConnMachineIn from) {
        this.dataField = from.getDataField();
        this.axis = from.getAxis();
        this.cmdField = from.getCmdField();
    }

    /**
      * Returns the value of {@code dataField}.
      * 
      * @return the value
      */
    public String getDataField() {
    
        return dataField;
    }
    
    /**
      * Returns the value of {@code axis}.
      * 
      * @return the value
      */
    public int getAxis() {
    
        return axis;
    }
    
    /**
      * Returns the value of {@code cmdField}.
      * 
      * @return the value
      */
    public String getCmdField() {
    
        return cmdField;
    }
    
    
    /**
     * Changes the value of {@code dataField}.
     * 
     * @param value the new value
     */
    public void setDataField(String value) {
    
        this.dataField = value;
    }
    
    /**
     * Changes the value of {@code axis}.
     * 
     * @param value the new value
     */
    public void setAxis(int value) {
    
        this.axis = value;
    }
    
    /**
     * Changes the value of {@code cmdField}.
     * 
     * @param value the new value
     */
    public void setCmdField(String value) {
    
        this.cmdField = value;
    }
    

    @Override
    public int hashCode() {
        int hc = 0;
        hc += getDataField() != null ? getDataField().hashCode() : 0;
        hc += Integer.hashCode(getAxis());
        hc += getCmdField() != null ? getCmdField().hashCode() : 0;
        return hc;
    }
    
    @Override
    public boolean equals(Object other) {
        boolean eq;
        if (other instanceof MyConnMachineIn) {
            MyConnMachineIn oth = (MyConnMachineIn) other;
            eq = true;
            eq &= getDataField() != null ? getDataField().equals(oth.getDataField()) : true;
            eq &= getAxis() == oth.getAxis();
            eq &= getCmdField() != null ? getCmdField().equals(oth.getCmdField()) : true;
        } else {
            eq = false;
        }
        return eq;
    }
    
    @Override
    public String toString() {
        return org.apache.commons.lang3.builder.ReflectionToStringBuilder.toString(this, 
            de.iip_ecosphere.platform.services.environment.IipStringStyle.SHORT_STRING_STYLE);
    }

}
