from json import JSONEncoder
import json
from iip import Serializer
import MyConnMachineIn

class MyConnMachineInSerializer(Serializer):
    """JSON transport serializer for MyConnMachineIn.
       Generated by: EASy-Producer."""
    
    class MyConnMachineInEncoder(JSONEncoder):
        """JSON encoder class for MyConnMachineIn.
        Generated by: EASy-Producer."""
    
        def default(self, o):
            """Provides access to the attributes in o.
            
            Parameters:
              - o -- the object to serialize
            Returns:
              dict
                the attributes
            """
            return o.__dict__
        
    
    def readFrom(data: bytes) -> MyConnMachineIn:
        """Turns bytes into an object.
        
        Parameters:
          - data -- the data bytes
        Returns:
          object
            the deserialized object
        """
    
        result = MyConnMachineIn()
        result.__dict__ = json.loads(data)
        return result

    def writeTo(source: MyConnMachineIn) -> bytes:
        """Turns an object into bytes.
        
        Parameters:
          - source -- the object
        Returns:
          bytes
            the serialized data bytes
        """
        
        return MyConnMachineInEncoder().encode(employee).encode("UTF-8")

