package iip.datatypes;


/**
 * Interface of the application data type MyConnMachineIn.
 * Generated by: EASy-Producer.
 */
public interface MyConnMachineIn {
 

    /**
      * Returns the value of {@code dataField}.
      * 
      * @return the value
      */
    public String getDataField();
    
    /**
      * Returns the value of {@code axis}.
      * 
      * @return the value
      */
    public int getAxis();
    
    /**
      * Returns the value of {@code cmdField}.
      * 
      * @return the value
      */
    public String getCmdField();
    
    
    /**
     * Changes the value of {@code dataField}.
     * 
     * @param value the new value
     */
    public void setDataField(String value);
    
    /**
     * Changes the value of {@code axis}.
     * 
     * @param value the new value
     */
    public void setAxis(int value);
    
    /**
     * Changes the value of {@code cmdField}.
     * 
     * @param value the new value
     */
    public void setCmdField(String value);
    
    

}
