package iip.datatypes;

import iip.datatypes.RtsaTestOutput;

/**
 * Implementation of the application data type RtsaTestOutput.
 * Generated by: EASy-Producer.
 */
public class RtsaTestOutputImpl implements RtsaTestOutput {
 
    private int id;
    
    private double value1;
    
    private double value2;
    
    private double confidence;
    
    private boolean prediction;
    

    /**
     * Default constructor. Fields are pre-allocated with default Java values.
     */
    public RtsaTestOutputImpl() {
    }
    
    /**
     * Copy constructor.
     * 
     * @param from the instance to copy the values from
     */
    public RtsaTestOutputImpl(RtsaTestOutput from) {
        this.id = from.getId();
        this.value1 = from.getValue1();
        this.value2 = from.getValue2();
        this.confidence = from.getConfidence();
        this.prediction = from.getPrediction();
    }

    @Override
    public int getId() {
    
        return id;
    }
    
    @Override
    public double getValue1() {
    
        return value1;
    }
    
    @Override
    public double getValue2() {
    
        return value2;
    }
    
    @Override
    public double getConfidence() {
    
        return confidence;
    }
    
    @Override
    public boolean getPrediction() {
    
        return prediction;
    }
    
    
    @Override
    public void setId(int value) {
    
        this.id = value;
    }
    
    @Override
    public void setValue1(double value) {
    
        this.value1 = value;
    }
    
    @Override
    public void setValue2(double value) {
    
        this.value2 = value;
    }
    
    @Override
    public void setConfidence(double value) {
    
        this.confidence = value;
    }
    
    @Override
    public void setPrediction(boolean value) {
    
        this.prediction = value;
    }
    

    @Override
    public int hashCode() {
        int hc = 0;
        hc += Integer.hashCode(getId());
        hc += Double.hashCode(getValue1());
        hc += Double.hashCode(getValue2());
        hc += Double.hashCode(getConfidence());
        hc += Boolean.hashCode(getPrediction());
        return hc;
    }
    
    @Override
    public boolean equals(Object other) {
        boolean eq;
        if (other instanceof RtsaTestOutput) {
            RtsaTestOutput oth = (RtsaTestOutput) other;
            eq = true;
            eq &= getId() == oth.getId();
            eq &= getValue1() == oth.getValue1();
            eq &= getValue2() == oth.getValue2();
            eq &= getConfidence() == oth.getConfidence();
            eq &= getPrediction() == oth.getPrediction();
        } else {
            eq = false;
        }
        return eq;
    }
    
    @Override
    public String toString() {
        return org.apache.commons.lang3.builder.ReflectionToStringBuilder.toString(this, 
            de.iip_ecosphere.platform.services.environment.IipStringStyle.SHORT_STRING_STYLE);
    }

}
