/*
 * generated by Xtext 2.34.0
 */
package de.uni_hildesheim.sse.vil.templatelang.validation;

import de.uni_hildesheim.sse.vil.expressions.validation.ExpressionDslValidator;
import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public abstract class AbstractTemplateLangValidator extends ExpressionDslValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
		result.add(de.uni_hildesheim.sse.vil.templatelang.templateLang.TemplateLangPackage.eINSTANCE);
		return result;
	}
}
