/*
 * generated by Xtext 2.34.0
 */
package de.uni_hildesheim.sse.vil.expressions.ide;


/**
 * Use this class to register ide components.
 */
public class ExpressionDslIdeModule extends AbstractExpressionDslIdeModule {
}
