package iip.interfaces;

import de.iip_ecosphere.platform.services.environment.*;
import iip.datatypes.*;

/**
 * IIP-Ecosphere service interface for 'Simple Kodex Data Source'.
 * Generated by: EASy-Producer.
 */
public interface SimpleKodexDataSourceInterface extends Service {

    public static final String SERVICE_ID = "SimpleKodexSource";

    
    /**
     * Synchronous source method, called to produce data items of type "KRec13".
     *
     * @return the data value to be ingested
     */
    public KRec13 produceKRec13();
    
}
