//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportPlanningService.GeneralTransportServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GeneralTransportServiceReference.IGeneralTransportService", CallbackContract=typeof(GeneralTransportServiceReference.IGeneralTransportServiceCallback))]
    public interface IGeneralTransportService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGeneralTransportService/InitiateTransport")]
        void InitiateTransport(string boxId, string binId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralTransportService/Dummy", ReplyAction="http://tempuri.org/IGeneralTransportService/DummyResponse")]
        void Dummy();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGeneralTransportServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGeneralTransportService/TransportFinished")]
        void TransportFinished(string boxId, string endDestId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGeneralTransportServiceChannel : GeneralTransportServiceReference.IGeneralTransportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeneralTransportServiceClient : System.ServiceModel.DuplexClientBase<GeneralTransportServiceReference.IGeneralTransportService>, GeneralTransportServiceReference.IGeneralTransportService {
        
        public GeneralTransportServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GeneralTransportServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GeneralTransportServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralTransportServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralTransportServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void InitiateTransport(string boxId, string binId) {
            base.Channel.InitiateTransport(boxId, binId);
        }
        
        public void Dummy() {
            base.Channel.Dummy();
        }
    }
}
