/*
 * generated by Xtext 2.34.0
 */
package de.uni_hildesheim.sse.vil.rt.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.uni_hildesheim.sse.vil.rt.RtVilRuntimeModule;
import de.uni_hildesheim.sse.vil.rt.RtVilStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RtVilIdeSetup extends RtVilStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RtVilRuntimeModule(), new RtVilIdeModule()));
	}
	
}
