package iip.serializers;

import java.io.IOException;
import de.iip_ecosphere.platform.transport.serialization.*;
import de.iip_ecosphere.platform.support.iip_aas.json.JsonUtils;
import iip.datatypes.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.JsonProcessingException;

/**
 * JSON transport serializer for MyConnPltfOut.
 * Generated by: EASy-Producer.
 */
public class MyConnPltfOutSerializer implements Serializer<MyConnPltfOut> {

    @Override             
    public MyConnPltfOut from(byte[] data) throws IOException {
        try {
            ObjectMapper objectMapper = new ObjectMapper();
            return objectMapper.readValue(data, MyConnPltfOutImpl.class);
        } catch (JsonProcessingException e) {
            throw new IOException(e);
        }
    }

    @Override    
    public byte[] to(MyConnPltfOut source) throws IOException {
        try {
            ObjectMapper objectMapper = new ObjectMapper();
            return objectMapper.writeValueAsBytes(source);
        } catch (JsonProcessingException e) {
            throw new IOException(e);
        }
    }

    @Override
    public MyConnPltfOut clone(MyConnPltfOut origin) throws IOException {
        return new MyConnPltfOutImpl(origin);
    }

    @Override
    public Class<MyConnPltfOut> getType() {
        return MyConnPltfOut.class;
    }

}

