package iip.serializers;

import java.io.IOException;
import de.iip_ecosphere.platform.transport.serialization.*;
import de.iip_ecosphere.platform.support.iip_aas.json.JsonUtils;
import iip.datatypes.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.JsonProcessingException;

/**
 * JSON transport serializer for MyConnPltfIn.
 * Generated by: EASy-Producer.
 */
public class MyConnPltfInSerializer implements Serializer<MyConnPltfIn> {

    @Override             
    public MyConnPltfIn from(byte[] data) throws IOException {
        try {
            ObjectMapper objectMapper = new ObjectMapper();
            return objectMapper.readValue(data, MyConnPltfInImpl.class);
        } catch (JsonProcessingException e) {
            throw new IOException(e);
        }
    }

    @Override    
    public byte[] to(MyConnPltfIn source) throws IOException {
        try {
            ObjectMapper objectMapper = new ObjectMapper();
            return objectMapper.writeValueAsBytes(source);
        } catch (JsonProcessingException e) {
            throw new IOException(e);
        }
    }

    @Override
    public MyConnPltfIn clone(MyConnPltfIn origin) throws IOException {
        return new MyConnPltfInImpl(origin);
    }

    @Override
    public Class<MyConnPltfIn> getType() {
        return MyConnPltfIn.class;
    }

}

