package iip.serializers;

import java.io.IOException;
import de.iip_ecosphere.platform.transport.serialization.*;
import de.iip_ecosphere.platform.support.iip_aas.json.JsonUtils;
import iip.datatypes.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.JsonProcessingException;

/**
 * JSON transport serializer for RtsaTestInput.
 * Generated by: EASy-Producer.
 */
public class RtsaTestInputImplSerializer implements Serializer<RtsaTestInputImpl> {

    @Override             
    public RtsaTestInputImpl from(byte[] data) throws IOException {
        try {
            ObjectMapper objectMapper = new ObjectMapper();
            return objectMapper.readValue(data, RtsaTestInputImpl.class);
        } catch (JsonProcessingException e) {
            throw new IOException(e);
        }
    }

    @Override    
    public byte[] to(RtsaTestInputImpl source) throws IOException {
        try {
            ObjectMapper objectMapper = new ObjectMapper();
            return objectMapper.writeValueAsBytes(source);
        } catch (JsonProcessingException e) {
            throw new IOException(e);
        }
    }

    @Override
    public RtsaTestInputImpl clone(RtsaTestInputImpl origin) throws IOException {
        return new RtsaTestInputImpl(origin);
    }

    @Override
    public Class<RtsaTestInputImpl> getType() {
        return RtsaTestInputImpl.class;
    }

}

