
from datetime import datetime

class MyConnPltfOut:
    """Interface of the application data type MyConnPltfOut. 
       Generated by: EASy-Producer."""
 
    
    def getCmdField(self) -> str:
        """Returns the value of {@code cmdField}.
        
           Returns:
             - the value of cmdField"""
        raise NotImplementedError
    
    
    def setCmdField(self, v: str):
        """Changes the value of {@code cmdField}.
        
           Parameters:
             - v -- the new value of cmdField"""
        raise NotImplementedError
    
