
from datetime import datetime

class MyConnPltfIn:
    """Interface of the application data type MyConnPltfIn. 
       Generated by: EASy-Producer."""
 
    
    def getAxis(self) -> int:
        """Returns the value of {@code axis}.
        
           Returns:
             - the value of axis"""
        raise NotImplementedError
    
    def getDataField(self) -> str:
        """Returns the value of {@code dataField}.
        
           Returns:
             - the value of dataField"""
        raise NotImplementedError
    
    
    def setAxis(self, v):
        """Changes the value of {@code axis}.
        
           Parameters:
             - v -- the new value of axis, may be of type int or the corresponding numpy type"""
        raise NotImplementedError
    
    def setDataField(self, v: str):
        """Changes the value of {@code dataField}.
        
           Parameters:
             - v -- the new value of dataField"""
        raise NotImplementedError
    
