from datatypes.MyConnMachineOut import MyConnMachineOut

from datetime import datetime

class MyConnMachineOutImpl(MyConnMachineOut):
    """Implementation of the application data type MyConnMachineOut. 
       Generated by: EASy-Producer."""
 
    cmdField: str
    
    def getCmdField(self) -> str:
        """Returns the value of {@code cmdField}.
        
           Returns:
             - the value of cmdField"""
        return self.cmdField
    
    
    def setCmdField(self, v: str):
        """Changes the value of {@code cmdField}.
        
           Parameters:
             - v -- the new value of cmdField"""
        self.cmdField = v
    
