/*
 * generated by Xtext 2.34.0
 */
package de.uni_hildesheim.sse.vil.buildlang.ui;

import com.google.inject.Injector;
import de.uni_hildesheim.sse.vil.buildlang.ui.internal.BuildlangActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VilBuildLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(BuildlangActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		BuildlangActivator activator = BuildlangActivator.getInstance();
		return activator != null ? activator.getInjector(BuildlangActivator.DE_UNI_HILDESHEIM_SSE_VIL_BUILDLANG_VILBUILDLANGUAGE) : null;
	}

}
