/*
* generated by Xtext
*/
package de.uni_hildesheim.sse.vil.rt;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RtVilStandaloneSetup extends RtVilStandaloneSetupGenerated{

	public static void doSetup() {
		new RtVilStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

