package iip.datatypes;

import iip.datatypes.RoutingConnIn;

/**
 * Implementation of the application data type RoutingConnIn.
 * Generated by: EASy-Producer.
 */
public class RoutingConnInImpl implements RoutingConnIn {
 
    private int intField;
    

    /**
     * Default constructor. Fields are pre-allocated with default Java values.
     */
    public RoutingConnInImpl() {
    }
    
    /**
     * Copy constructor.
     * 
     * @param from the instance to copy the values from
     */
    public RoutingConnInImpl(RoutingConnIn from) {
        this.intField = from.getIntField();
    }

    @Override
    public int getIntField() {
    
        return intField;
    }
    
    
    @Override
    public void setIntField(int value) {
    
        this.intField = value;
    }
    

    @Override
    public int hashCode() {
        int hc = 0;
        hc += Integer.hashCode(getIntField());
        return hc;
    }
    
    @Override
    public boolean equals(Object other) {
        boolean eq;
        if (other instanceof RoutingConnIn) {
            RoutingConnIn oth = (RoutingConnIn) other;
            eq = true;
            eq &= getIntField() == oth.getIntField();
        } else {
            eq = false;
        }
        return eq;
    }
    
    @Override
    public String toString() {
        return org.apache.commons.lang3.builder.ReflectionToStringBuilder.toString(this, 
            de.iip_ecosphere.platform.services.environment.IipStringStyle.SHORT_STRING_STYLE);
    }

}
