/*
 * generated by Xtext
 */
package de.uni_hildesheim.sse.vil.templatelang;

import de.uni_hildesheim.sse.vil.expressions.values.VilValueConverters;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TemplateLangRuntimeModule extends de.uni_hildesheim.sse.vil.templatelang.AbstractTemplateLangRuntimeModule {

    /**
     * Configures the value converter factory.
     * 
     * @return the class denoting the value converters factory
     */
    public Class<? extends org.eclipse.xtext.conversion.IValueConverterService> bindIValueConverterService() {
        return VilValueConverters.class;
    }

}
