/*
 * generated by Xtext
 */
package de.uni_hildesheim.sse.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.uni_hildesheim.sse.ui.internal.IvmlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IvmlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return IvmlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return IvmlActivator.getInstance().getInjector(IvmlActivator.DE_UNI_HILDESHEIM_SSE_IVML);
	}
	
}
